const vegetables = [
  { key: 1, name: "POTATO" },
  { key: 2, name: "SMALL POTATO" },
  { key: 3, name: "ONION" },
  { key: 4, name: "COCONUT" },
  { key: 5, name: "TOMATO" },
  { key: 6, name: "CARROT" },
  { key: 7, name: "CUCUMBER" },
  { key: 8, name: "CABBAGE" },
  { key: 9, name: "BEETROOT" },
  { key: 10, name: "GREEN CHILLI" },
  { key: 11, name: "GINGER" },
  { key: 12, name: "TENDLI" },
  { key: 13, name: "SURAN" },
  { key: 14, name: "DUDHI" },
  { key: 15, name: "SENGA" },
  { key: 16, name: "RAW BANANA" },
  { key: 17, name: "KARELAA" },
  { key: 18, name: "RAW MANGO" },
  { key: 19, name: "RAW PAPAYA" },
  { key: 20, name: "PAPADI" },
  { key: 21, name: "YELLOW LEMON" },
  { key: 22, name: "GREEN LEMON" },
  { key: 23, name: "FRENCH BEANS" },
  { key: 24, name: "LADY FINGER" },
  { key: 25, name: "BRINJAL" },
  { key: 26, name: "GREEN CAPSICUM" },
  { key: 27, name: "GARLIC PEELED" },
  { key: 28, name: "CAULIFLOWER" },
  { key: 29, name: "LAMBA PARVAL" },
  { key: 30, name: "SMALL PARVAL" },
  { key: 31, name: "CORIANDER LEAVES" },
  { key: 32, name: "METHI" },
  { key: 33, name: "SPRING ONION" },
  { key: 34, name: "DILL LEAVES" },
  { key: 35, name: "MINT" },
  { key: 36, name: "CURRY LEAVES" },
  { key: 37, name: "SPINACH" },
  { key: 38, name: "TURAI/GALKA" },
  { key: 39, name: "GAWAR" },
  { key: 40, name: "CHAWLI" },
  { key: 41, name: "WAFER POTATO" },
  { key: 42, name: "RED PUMPKIN" },
  { key: 43, name: "GREEN PEA" },
  { key: 44, name: "BHAVNAGRI" },
  { key: 45, name: "RADDISH" },
  { key: 46, name: "BANANA LEAVES" },
  { key: 47, name: "RED CHILLY" },
  { key: 48, name: "WHITE ONION" },
  { key: 49, name: "SWEET POTATO" },
  { key: 50, name: "SWEET LIME" },
  { key: 51, name: "ORANGE MALTA" },
  { key: 52, name: "POMEGRANATE" },
  { key: 53, name: "WATERMELON" },
  { key: 54, name: "MUSK MELON" },
  { key: 55, name: "DRAGON FRUIT" },
  { key: 56, name: "GARPE FRUITE" },
  { key: 57, name: "APPLE" },
  { key: 58, name: "PAPAYA" },
  { key: 59, name: "CALIFORNIA GRAPES" },
  { key: 60, name: "KIWI" },
  { key: 61, name: "BANANA" },
  { key: 62, name: "PEAR" },
  { key: 63, name: "BLACK PLUM" },
  { key: 64, name: "PASSION FRUIT" },
  { key: 65, name: "GREEN APPLE" },
  { key: 66, name: "BLUEBERRY" },
  { key: 67, name: "BLACKBERRY" },
  { key: 68, name: "RASPBERRY" },
  { key: 69, name: "MULBERRY" },
  { key: 70, name: "RED CURRENT" },
  { key: 71, name: "PEACH" },
  { key: 72, name: "BUTTON MUSHROOM" },
  { key: 73, name: "BABY CORN" },
  { key: 74, name: "BROCCOLI" },
  { key: 75, name: "CHINESE CABBAGE" },
  { key: 76, name: "RED CAPSICUM" },
  { key: 77, name: "YELLOW CAPSICUM" },
  { key: 78, name: "ICEBERG LETTUCE" },
  { key: 79, name: "GREEN ZUCCHINI" },
  { key: 80, name: "YELLOW ZUCCHINI" },
  { key: 81, name: "AMERICAN SWEETCORN" },
  { key: 82, name: "RED CABBAGE" },
  { key: 83, name: "YAM BEAN" },
  { key: 84, name: "TARO ROOT (IMP)" },
  { key: 85, name: "SNOW PEA (IMP)" },
  { key: 86, name: "KING CHILLY(THAI RED CHILLY)" },
  { key: 87, name: "LOTUS ROOT (IND)" },
  { key: 88, name: "LOTUS ROOT (IMP)" },
  { key: 89, name: "ITALIAN LEMON" },
  { key: 90, name: "PURPLE POTATO" },
  { key: 91, name: "LEMON GRASS" },
  { key: 92, name: "BOK CHOY" },
  { key: 93, name: "LEEKS" },
  { key: 94, name: "CELERY" },
  { key: 95, name: "ENGLISH CUCUMBER" },
  { key: 96, name: "THAI GINGER" },
  { key: 97, name: "ROMAINE LETTUCE" },
  { key: 98, name: "ROCKET LEAVES" },
  { key: 99, name: "LOLLO ROSSO LETTUCE" },
  { key: 100, name: "AMERICAN KALE" },
  { key: 101, name: "BEANS SPROUT" },
  { key: 102, name: "CHERRY TOMATO" },
  { key: 103, name: "BASIL LEAVES" },
  { key: 104, name: "THAI BIRD CHILLI" },
  { key: 105, name: "KAFFIR LIME LEAVES" },
  { key: 106, name: "PARSLEY" },
  { key: 107, name: "KAFFIR LIME FRUIT" },
  { key: 108, name: "CHIVES" },
  { key: 109, name: "THYME" },
  { key: 110, name: "ROSEMARY" },
  { key: 111, name: "ALFA ALFA" },
  { key: 112, name: "OREGANO" },
  { key: 113, name: "SAGE" },
  { key: 114, name: "BABY CARROT" },
  { key: 115, name: "BABY POKCHOY" },
  { key: 116, name: "SWISS CHARD" },
  { key: 117, name: "BABY ROCKET" },
  { key: 118, name: "BABY SPINACH" },
  { key: 119, name: "MICROGREEN" },
  { key: 120, name: "EDIBLE FLOWER" },
  { key: 121, name: "OYSTER MUSHROOM" },
  { key: 122, name: "PORTOBELLO MUSHROOM" },
  { key: 123, name: "SHIITAKE MUSHROOM" },
  { key: 124, name: "ENOKI MUSHROOM" },
  { key: 125, name: "SHIMEJI MUSHROOM (WHITE)" },
  { key: 126, name: "SHIMEJI MUSHROOM (BROWN)" },
  { key: 127, name: "KING OYSTER MUSHROOM" },
  { key: 128, name: "ASPARAGUS (IMP)" },
  { key: 129, name: "ASPARAGUS (IND)" },
  { key: 130, name: "ASPARAGUS WHITE JUMBOO" },
  { key: 131, name: "ASPARAGUS GREEN JUMBOO" },
  { key: 132, name: "AVOCADO (IMP)" },
  { key: 133, name: "AVOCADO (IND)" },
];

const mappedVegetables = new Map(
  vegetables.map((item, index) => [item.name, index])
);

export default mappedVegetables