const vegetableList = {
  potato: 'आलू',
  'small potato': 'छोटे आलू',
  onion: 'प्याज',
  'small onion': 'छोटे प्याज',
  'garlic peeled (regular)': 'लहसुन छिला हुआ (साधारण)',
  'garlic peeled (chaina)': 'लहसुन छिला हुआ (चाइना)',
  'whole garlic': 'पूरा लहसुन',
  coconut: 'नारियल',
  tomato: 'टमाटर',
  'french beans': 'फ्रेंच बीन्स',
  'lady finger': 'भिंडी',
  'lady finger (small)': 'छोटी भिंडी',
  'brinjal (bharta)': 'बैंगन (भर्ता)',
  'brinjal (kata)': 'बैंगन (कटा हुआ)',
  'green capsicum': 'हरी शिमला मिर्च',
  carrot: 'गाजर',
  cucumber: 'खीरा',
  cabbage: 'पत्ता गोभी',
  cauliflower: 'फूलगोभी',
  'beet root': 'चुकंदर',
  'green chilli': 'हरी मिर्च',
  ginger: 'अदरक',
  tendli: 'टिंडली',
  suran: 'सूरन',
  dudhi: 'लौकी',
  'lamba parwar': 'लंबा परवर',
  'small parwar': 'छोटा परवर',
  senga: 'सेंगा',
  spinach: 'पालक',
  'spring onion': 'हरे प्याज',
  'raw banana': 'कच्चा केला',
  'coriander leaves': 'धनिया पत्ते',
  mint: 'पुदीना',
  'curry leaves': 'करी पत्ते',
  'yellow lemon': 'पीला नींबू',
  'green lemon': 'हरा नींबू',
  methi: 'मेथी',
  karelaa: 'करेला',
  'raw mango': 'कच्चा आम',
  'dill leaves': 'सुआ पत्ते',
  'raw papaya': 'कच्चा पपीता',
  papadi: 'पापड़ी',
  'turai/galta': 'तोरी/गलता',
  gawar: 'गवार',
  chawli: 'चवली',
  'wafer potato': 'वाफर आलू',
  'red pumpkin': 'लाल कद्दू',
  'green pea': 'हरी मटर',
  bhavnagri: 'भवांगरी मिर्च',
  raddish: 'मूली',
  'banana leaves': 'केले के पत्ते',
  'red chilly': 'लाल मिर्च',
  'white onion': 'सफेद प्याज',
  'sweet potato': 'शकरकंद',
  'button mushroom': 'मशरूम',
  'oyster mushroom': 'ऑयस्टर मशरूम',
  'portobello mushroom (ind)': 'पोर्टोबेलो मशरूम (भारतीय)',
  'portobello mushroom (imp)': 'पोर्टोबेलो मशरूम (आयातित)',
  'shiitake mushroom (fresh)': 'शिटाक मशरूम (ताजा)',
  'shiitake mushroom (dry)': 'शिटाक मशरूम (सूखा)',
  'enoki mushroom': 'एनोकि मशरूम',
  'shimeji mushroom (white)': 'शिमेजी मशरूम (सफेद)',
  'shimeji mushroom (brown)': 'शिमेजी मशरूम (भूरा)',
  'king oyster mushroom': 'किंग ऑयस्टर मशरूम',
  'asparagus (imp)': 'शतावरी (आयातित)',
  'asparagus (ind)': 'शतावरी (भारतीय)',
  'asparagus white jumbo': 'सफेद शतावरी जंबो',
  'asparagus green jumbo': 'हरी शतावरी जंबो',
  'avocado (imp)': 'एवोकाडो (आयातित)',
  'avocado (ind)': 'एवोकाडो (भारतीय)',
  'baby corn': 'बेबी कॉर्न',
  broccoli: 'ब्रोकोली',
  'chinese cabbage': 'चीनी पत्ता गोभी',
  'red capsicum': 'लाल शिमला मिर्च',
  'yellow capsicum': 'पीली शिमला मिर्च',
  'iceberg lettuce': 'आइसबर्ग लेट्यूस',
  'green zucchini': 'हरी तोरी',
  'yellow zucchini': 'पीली तोरी',
  'lemon grass': 'नींबू घास',
  pokchoy: 'पोकचोय',
  'romaine lettuce': 'रोमेन लेट्यूस',
  'roquette leaves': 'रॉकेट पत्तियां',
  'beans sprout': 'मूंग अंकुरित',
  leeks: 'लीक',
  celery: 'अजवाइन',
  'lollo rosso lettuce': 'लोलो रोसो लेट्यूस',
  'cherry tomato': 'चेरी टमाटर',
  'basil leaves': 'तुलसी पत्तियां',
  'thai bird chilli': 'थाई बर्ड मिर्च',
  'kaffir lime leaves': 'काफिर चूना पत्तियां',
  'galangal (thai ginger)': 'गलांगल (थाई अदरक)',
  chives: 'चाइव्स',
  thyme: 'थाइम',
  rosemary: 'रोsemary',
  'curled parsley': 'घुमावदार अजमोद',
  'flat parsley': 'फ्लैट अजमोद',
  'american sweetcorn': 'अमेरिकी मीठा मक्का',
  'red cabbage': 'लाल पत्ता गोभी',
  'american kale': 'अमेरिकी केल',
  'kaffir lime fruit (makroot)': 'काफिर नींबू (मकरूट)',
  'english cucumber': 'अंग्रेजी खीरा',
  microgreen: 'माइक्रोग्रीन',
  'edible flowers': 'खाने योग्य फूल',
  'lotus root (ind)': 'कमल ककड़ी (भारतीय)',
  'lotus root (imp)': 'कमल ककड़ी (आयातित)',
  'italian lemon': 'इटालियन नींबू',
  'purple potato': 'बैंगनी आलू',
  'baby rocket': 'बेबी रॉकेट',
  'baby spinach': 'बेबी पालक',
  'baby carrot': 'बेबी गाजर',
  'baby pokchoy': 'बेबी पोकचोय',
  'swiss chard': 'स्विस चार्ड',
  oregano: 'ओरेगानो',
  sage: 'सेज',
  'yam bean': 'जिमीकंद',
  'taro root (imp)': 'अरबी की जड़ (आयातित)',
  'snow pea (imp)': 'स्नो मटर (आयातित)',
  'king chilly (thai red chilly)': 'किंग मिर्ची (थाई लाल मिर्च)',
  'alfa alfa': 'अल्फा-अल्फा',
  'edamame (imp)': 'एडामामे (आयातित)',
  'red raddish': 'लाल मूली',
  'red jalapino': 'लाल जलपीनो',
  jalapino: 'जलपीनो',
  'edamame peeled': 'एडामामे छिला हुआ',
  fennel: 'सौंफ',
  'sweet orange potato (imp)': 'मीठा नारंगी आलू (आयातित)',
  'sweet purple potato (imp)': 'मीठा बैंगनी आलू (आयातित)',
  'baby rocket (imp)': 'बेबी रॉकेट (आयातित)',
  'baby spinach (imp)': 'बेबी पालक (आयातित)',
  'sweet lime': 'मौसंबी',
  'orange malta': 'माल्टा संतरा',
  apple: 'सेब',
  pineapple: 'अनानास',
  papaya: 'पपीता',
  'california grapes': 'कैलिफ़ोर्निया अंगूर',
  kiwi: 'कीवी',
  pomegranate: 'अनार',
  watermelon: 'तरबूज',
  banana: 'केला',
  'musk melon': 'खरबूजा',
  'dragon fruit': 'ड्रैगन फ्रूट',
  pear: 'नाशपाती',
  'black plum': 'जामुन',
  'passion fruit': 'पैशन फ्रूट',
  'grape fruit': 'चकोतरा',
  'green apple': 'हरा सेब',
  'blue berries': 'ब्लू बेरी',
  'black berries': 'ब्लैक बेरी',
  'rasp berries': 'रास्पबेरी',
  'mul berries': 'शहतूत',
  'red current': 'लाल करंट',
  peach: 'आड़ू',
  none: '',
};

export default vegetableList;
