const vegetableList = {
  "onion": "प्याज",
  "tomato": "टमाटर",
  "potato": "आलू",
  "cauliflower": "फूलगोभी",
  "cabbage": "पत्ता गोभी",
  "spinach": "पालक",
  "carrot": "गाजर",
  "radish": "मूली",
  "garlic": "लहसुन",
  "ginger": "अदरक",
  "peas": "मटर",
  "eggplant": "बैंगन",
  "okra": "भिंडी",
  "pumpkin": "कद्दू",
  "cucumber": "खीरा",
  "capsicum": "शिमला मिर्च",
  "bottle gourd": "लौकी",
  "bitter gourd": "करेला",
  "sweet potato": "शकरकंद",
  "beetroot": "चुकंदर",
  "green chili": "हरी मिर्च",
  "mushroom": "मशरूम",
  "fenugreek": "मेथी",
  "coriander": "धनिया",
  "mint": "पुदीना",
  "turnip": "शलगम",
  "zucchini": "तोरी",
  "broccoli": "ब्रोकोली",
  "lettuce": "सलाद पत्ता",
  "celery": "अजवाइन",
  "spring onion": "हरे प्याज़",
  "asparagus": "शतावरी",
  "artichoke": "हाथी चक्री",
  "leek": "लीक",
  "kale": "काले",
  "mustard greens": "सरसों का साग",
  "drumstick": "सहजन",
  "snake gourd": "चिचिंडा",
  "ash gourd": "पेठा",
  "yam": "रतालू",
  "turmeric": "हल्दी",
  "amaranth leaves": "चौलाई के पत्ते",
  "curry leaves": "कड़ी पत्ता",
  "dill": "सुआ",
  "parsley": "अजमोद",
  "bay leaf": "तेज पत्ता",
  "basil": "तुलसी",
  "water spinach": "कलमी साग",
  "ridge gourd": "तोरी",
  "ivy gourd": "कुंदरू",
  "cluster beans": "गवार फली",
  "fennel": "सौंफ",
  "beans": "फली",
  "none":""
};

export default vegetableList